== angularjs-addon
:idprefix: id_ 
The angularjs-addon enables developers to automate several tasks in the construction of applications that use AngularJS, in JBoss Forge.
This addon provides *standalone* functionality, and it can be re-used in other addons.
        
=== Dependencies:
=== Depends on
[options="header"]
|===
|Addon |Exported |Optional
|scaffold-spi
|no
|no
|javaee
|no
|no
|templates
|no
|no
|text
|no
|no
|convert
|no
|no
|parser-java
|no
|no
|cdi
|no
|no
|===

== Setup
This Addon requires the following installation steps.

=== Add configuration to pom.xml
To use this addon, you must add it as a dependency in the *pom.xml* of your `forge-addon` classified artifact:
(Make sure the dependency is put all the way to the left, and uses 3 spaces for indentation of GAV)
[source,xml]
----
<dependency>
   <groupId>org.jboss.forge.addon.angularjs</groupId>
   <artifactId>angularjs-addon</artifactId>
   <classifier>forge-addon</classifier>
   <version>${version}</version>
</dependency>
----
== Features
* Scaffold web-apps from JPA entities. The generated scaffold uses a thick-client based on AngularJS, and a JAX-RS RESTful backend.